apiVersion: workloadidentity.azure.micosolutions.se/v1alpha1
kind: WorkloadIdentity
metadata:
  name: ${WORKLOAD_IDENTITY_NAME}
  namespace: ${NAMESPACE}
spec:
  azure:
    userAssignedIdentityName: ${AZURE_USER_ASSIGNED_IDENTITY_NAME}
    federatedIdentityCredentialName: ${AZURE_FEDERATED_IDENTITY_CREDENTIAL_NAME}
  serviceAccount:
    name: ${SERVICE_ACCOUNT_NAME}
  deletionPolicy: ${WORKLOAD_IDENTITY_DELETION_POLICY}
