---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-workloadidentity-azure-micosolutions-se-v1alpha1-oidcissuer
  failurePolicy: Fail
  name: voidcissuer-v1alpha1.workloadidentity.azure.micosolutions.se
  rules:
  - apiGroups:
    - workloadidentity.azure.micosolutions.se
    apiVersions:
    - v1alpha1
    operations:
    - DELETE
    resources:
    - oidcissuers
  sideEffects: None
