apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../default

patches:
- path: manager_azure_scope_patch.yaml
  target:
    kind: Deployment
    labelSelector: control-plane=controller-manager
