---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - config.openshift.io
  resources:
  - authentications
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - workloadidentity.azure.micosolutions.se
  resources:
  - oidcissuers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - workloadidentity.azure.micosolutions.se
  resources:
  - oidcissuers/finalizers
  verbs:
  - update
- apiGroups:
  - workloadidentity.azure.micosolutions.se
  resources:
  - oidcissuers/status
  verbs:
  - get
  - patch
  - update
