apiVersion: workloadidentity.azure.micosolutions.se/v1alpha1
kind: WorkloadIdentity
metadata:
  labels:
    app.kubernetes.io/name: azure-workload-identity-operator
    app.kubernetes.io/managed-by: kustomize
  name: workloadidentity-sample
spec:
  azure:
    subscriptionID: 00000000-0000-0000-0000-000000000000
    location: swedencentral
    resourceGroupName: rg-azwi-sample
    userAssignedIdentityName: uami-azwi-sample
    federatedIdentityCredentialName: fic-azwi-sample
  serviceAccount:
    name: azwi-sample
  deletionPolicy: Retain
