apiVersion: workloadidentity.azure.micosolutions.se/v1alpha1
kind: OIDCIssuer
metadata:
  labels:
    app.kubernetes.io/name: azure-workload-identity-operator
    app.kubernetes.io/managed-by: kustomize
  name: default
spec:
  azure:
    storageAccountName: oidcissuerdemo123
    blobContainerName: oidc
  signingKey:
    secretRef:
      namespace: kube-system
      name: service-account-signing-key
      key: tls.key
  openShift:
    updateServiceAccountIssuer: false
  deletionPolicy: Retain
