azure:
  tenantId: 00000000-0000-0000-0000-000000000000
  subscriptionId: 00000000-0000-0000-0000-000000000000
  resourceGroupName: rg-platform-workload-identity
  location: swedencentral
  credentials:
    # This Secret is externally managed and its values must not be stored in Git.
    secretRef:
      name: azure-workload-identity-operator-azure-credentials
      keys:
        clientId: AZURE_CLIENT_ID
        tenantId: AZURE_TENANT_ID
        clientSecret: AZURE_CLIENT_SECRET
